# Generated by Django 4.0.6 on 2022-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='country_found',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
