# Generated by Django 4.0.6 on 2022-07-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_squirrel_country_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='country_found',
            field=models.CharField(max_length=100, verbose_name='Countries Found'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(choices=[('R', 'Ran around'), ('C', 'Climbed trees'), ('S', 'Stole from the garden')], default='R', max_length=1)),
                ('squirrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.squirrel')),
            ],
        ),
    ]
