# Generated by Django 4.0.6 on 2022-07-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_squirrel_country_found_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('foodtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='squirrel',
            name='food',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
